title: Bhumil

sass:
  sass_dir: _sass
  style: compressed # or expanded for development

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

include:
  - '_pages'

permalink: /posts/:title/

plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/posts/page:num/"